def sample_grid():
    return [['p', 'o', 's', 's', 'e', 's', 's', 'e', 'd', '#'],
         ['#', 'i', '#', 'a', '#', 't', '#', 'l', '#', 'c'],
         ['i', 'n', 't', 'i', 'm', 'a', 't', 'e', 'l', 'y'],
         ['#', 'k', '#', 'd', '#', 'r', '#', 'v', '#', 'b'],
         ['s', '#', 't', '#', 'b', 'r', 'e', 'e', 'z', 'e'],
         ['c', 'o', 'w', 'b', 'o', 'y', '#', 'n', '#', 'r'],
         ['a', '#', 'e', '#', 'w', '#', 'p', '#', 'e', '#'],
         ['b', 'e', 'l', 'i', 'e', 'v', 'a', 'b', 'l', 'e'],
         ['s', '#', 'v', '#', 'r', '#', 'r', '#', 's', '#'],
         ['#', 'p', 'e', 'r', 's', 'u', 'a', 'd', 'e', 'd']]

def sample_clues():
    return {'hor': {(0, 0): ['To have'],
          (2, 0): ['In an intimate manner'],
          (4, 4): ['To move casually, in a carefree manner'],
          (5,
           0): ['A man who tends free-range cattle, especially in the American West'],
          (7, 0): ['credible'],
          (9,
           1): ['To successfully convince to agree to, accept, or do something, usually through reasoning and verbal influence']},
         'vert': {(0,
           1): ['Of a pig or in imitation thereof, to make its characteristic sound'],
          (0, 3): ['To pronounce'],
          (0, 5): ['Having stars visible'],
          (0, 7): ['A cricket team of eleven players'],
          (1,
           9): ['Everything having to do with the Internet considered collectively'],
          (4, 0): ['To become covered by a scab or scabs'],
          (4, 2): ['A group of twelve items'],
          (4, 4): ['A young hawk, when it begins to leave the nest'],
          (6,
           6): ['A former subunit of currency in several countries in the Ottoman/Turkish and Yugoslav regions'],
          (6, 8): ['or else']}}



def sample_word_cells():
    return {'hor': {(0, 0): [(0, 0),
           (0, 1),
           (0, 2),
           (0, 3),
           (0, 4),
           (0, 5),
           (0, 6),
           (0, 7),
           (0, 8)],
          (2, 0): [(2, 0),
           (2, 1),
           (2, 2),
           (2, 3),
           (2, 4),
           (2, 5),
           (2, 6),
           (2, 7),
           (2, 8),
           (2, 9)],
          (4, 4): [(4, 4), (4, 5), (4, 6), (4, 7), (4, 8), (4, 9)],
          (5, 0): [(5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5)],
          (7, 0): [(7, 0),
           (7, 1),
           (7, 2),
           (7, 3),
           (7, 4),
           (7, 5),
           (7, 6),
           (7, 7),
           (7, 8),
           (7, 9)],
          (9, 1): [(9, 1),
           (9, 2),
           (9, 3),
           (9, 4),
           (9, 5),
           (9, 6),
           (9, 7),
           (9, 8),
           (9, 9)]},
         'vert': {(0, 1): [(0, 1), (1, 1), (2, 1), (3, 1)],
          (0, 3): [(0, 3), (1, 3), (2, 3), (3, 3)],
          (0, 5): [(0, 5), (1, 5), (2, 5), (3, 5), (4, 5), (5, 5)],
          (0, 7): [(0, 7), (1, 7), (2, 7), (3, 7), (4, 7), (5, 7)],
          (1, 9): [(1, 9), (2, 9), (3, 9), (4, 9), (5, 9)],
          (4, 0): [(4, 0), (5, 0), (6, 0), (7, 0), (8, 0)],
          (4, 2): [(4, 2), (5, 2), (6, 2), (7, 2), (8, 2), (9, 2)],
          (4, 4): [(4, 4), (5, 4), (6, 4), (7, 4), (8, 4), (9, 4)],
          (6, 6): [(6, 6), (7, 6), (8, 6), (9, 6)],
          (6, 8): [(6, 8), (7, 8), (8, 8), (9, 8)]}}

def sample_placed_words():
    return ['intimately',
         'cyber',
         'said',
         'possessed',
         'oink',
         'eleven',
         'breeze',
         'starry',
         'bowers',
         'cowboy',
         'twelve',
         'persuaded',
         'believable',
         'scabs',
         'else',
         'para']